export const OGAMEX_ASSET_CATEGORIES = {
  BACKGROUNDS: "backgrounds",
  CONTENT: "content",
  FLEET: "fleet",
  INTERFACE: "interface",
  BUILDINGS: "buildings",
  RESEARCH: "research",
  UNITS: "units",
  HEADERS: "headers",
  PLANETARY: "planetary",
  GENERATED: "generated",
} as const;

export type OgamexAssetCategory =
  (typeof OGAMEX_ASSET_CATEGORIES)[keyof typeof OGAMEX_ASSET_CATEGORIES];

export interface OgamexAssetReference {
  id: string;
  name: string;
  category: OgamexAssetCategory;
  path: string;
  sourcePath: string;
  description: string;
  tags: string[];
}

export const OGAMEX_ASSET_COLLECTIONS: readonly OgamexAssetReference[] = [
  {
    id: "ogamex-bg-main",
    name: "Command Background",
    category: OGAMEX_ASSET_CATEGORIES.BACKGROUNDS,
    path: "/assets/ogamex/backgrounds/background-large.jpg",
    sourcePath: "ogamex-source/public/img/bg/background-large.jpg",
    description: "Primary OGameX starfield background adapted for the in-game shell.",
    tags: ["background", "shell", "hero"],
  },
  {
    id: "ogamex-content-research",
    name: "Research Overview",
    category: OGAMEX_ASSET_CATEGORIES.CONTENT,
    path: "/assets/ogamex/content/research_200.jpg",
    sourcePath: "ogamex-source/public/img/content/research_200.jpg",
    description: "Research feature artwork for science- and lab-focused panels.",
    tags: ["research", "lab", "feature"],
  },
  {
    id: "ogamex-content-ships",
    name: "Fleet Overview",
    category: OGAMEX_ASSET_CATEGORIES.CONTENT,
    path: "/assets/ogamex/content/ships_200.jpg",
    sourcePath: "ogamex-source/public/img/content/ships_200.jpg",
    description: "Ship overview art suited for fleet command and compendium pages.",
    tags: ["fleet", "ships", "feature"],
  },
  {
    id: "ogamex-content-ships-compact",
    name: "Compact Fleet Overview",
    category: OGAMEX_ASSET_CATEGORIES.CONTENT,
    path: "/assets/ogamex/content/ships_80.png",
    sourcePath: "ogamex-source/public/img/content/ships_80.png",
    description: "Compact fleet artwork for tight stat cards and secondary command panels.",
    tags: ["fleet", "ships", "compact"],
  },
  {
    id: "ogamex-content-defense",
    name: "Defense Panel",
    category: OGAMEX_ASSET_CATEGORIES.CONTENT,
    path: "/assets/ogamex/content/defense_80.png",
    sourcePath: "ogamex-source/public/img/content/defense_80.png",
    description: "Compact defense icon artwork from OGameX.",
    tags: ["defense", "combat", "icon"],
  },
  {
    id: "ogamex-content-sprite",
    name: "Content Sprite Sheet",
    category: OGAMEX_ASSET_CATEGORIES.INTERFACE,
    path: "/assets/ogamex/content/sprite.jpg",
    sourcePath: "ogamex-source/public/img/content/sprite.jpg",
    description: "Sprite sheet used for classic OGameX content presentation.",
    tags: ["sprite", "interface", "classic"],
  },
  {
    id: "ogamex-layout-detail-sprites",
    name: "Detail UI Sprite Sheet",
    category: OGAMEX_ASSET_CATEGORIES.INTERFACE,
    path: "/assets/ogamex/layout/detail-spriteset.png",
    sourcePath: "ogamex-source/public/img/layout/detail-spriteset.png",
    description: "Detail panel sprite sheet from the original OGameX interface.",
    tags: ["ui", "sprite", "panels"],
  },
  {
    id: "ogamex-layout-ui-elements",
    name: "UI Elements Sprite Sheet",
    category: OGAMEX_ASSET_CATEGORIES.INTERFACE,
    path: "/assets/ogamex/layout/sprite_ui_elements.png",
    sourcePath: "ogamex-source/public/img/layout/sprite_ui_elements.png",
    description: "General interface sprite sheet reused for status and chrome inspiration.",
    tags: ["ui", "sprite", "chrome"],
  },
  {
    id: "ogamex-fleet-attack",
    name: "Attack Mission",
    category: OGAMEX_ASSET_CATEGORIES.FLEET,
    path: "/assets/ogamex/fleet/mission-attack.gif",
    sourcePath: "ogamex-source/public/img/fleet/1.gif",
    description: "Animated attack mission indicator.",
    tags: ["fleet", "attack", "mission"],
  },
  {
    id: "ogamex-fleet-transport",
    name: "Transport Mission",
    category: OGAMEX_ASSET_CATEGORIES.FLEET,
    path: "/assets/ogamex/fleet/mission-transport.gif",
    sourcePath: "ogamex-source/public/img/fleet/3.gif",
    description: "Animated transport mission indicator.",
    tags: ["fleet", "transport", "mission"],
  },
  {
    id: "ogamex-fleet-spy",
    name: "Espionage Mission",
    category: OGAMEX_ASSET_CATEGORIES.FLEET,
    path: "/assets/ogamex/fleet/mission-spy.gif",
    sourcePath: "ogamex-source/public/img/fleet/6.gif",
    description: "Animated espionage mission indicator.",
    tags: ["fleet", "spy", "mission"],
  },
  {
    id: "ogamex-galaxy-activity",
    name: "Galaxy Activity",
    category: OGAMEX_ASSET_CATEGORIES.INTERFACE,
    path: "/assets/ogamex/galaxy/activity.gif",
    sourcePath: "ogamex-source/public/img/galaxy/activity.gif",
    description: "Galaxy activity signal used for live map feedback.",
    tags: ["galaxy", "activity", "indicator"],
  },
  {
    id: "ogamex-galaxy-ajax",
    name: "Ajax Indicator",
    category: OGAMEX_ASSET_CATEGORIES.INTERFACE,
    path: "/assets/ogamex/galaxy/ajax_indicator.gif",
    sourcePath: "ogamex-source/public/img/galaxy/ajax_indicator.gif",
    description: "Loading indicator from OGameX galaxy interactions.",
    tags: ["loading", "galaxy", "indicator"],
  },
  {
    id: "ogamex-header-defense",
    name: "Defense Header",
    category: OGAMEX_ASSET_CATEGORIES.CONTENT,
    path: "/assets/ogamex/headers/defense/defense.jpg",
    sourcePath: "ogamex-source/public/img/headers/defense/defense.jpg",
    description: "Defense page header artwork used as a shell banner accent.",
    tags: ["header", "defense", "banner"],
  },
  {
    id: "ogamex-header-resources-desert",
    name: "Desert Resource Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/resources/desert_1_2_3_4.jpg",
    sourcePath: "ogamex-source/public/img/headers/resources/desert_1_2_3_4.jpg",
    description: "Resource extraction header for arid surface economies.",
    tags: ["header", "resources", "desert"],
  },
  {
    id: "ogamex-header-resources-ice",
    name: "Ice Resource Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/resources/ice_1_2_3_4.jpg",
    sourcePath: "ogamex-source/public/img/headers/resources/ice_1_2_3_4.jpg",
    description: "Frozen-world resource header for mining and deuterium-heavy layouts.",
    tags: ["header", "resources", "ice"],
  },
  {
    id: "ogamex-header-resources-jungle",
    name: "Jungle Resource Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/resources/jungle_1_2_3_4.jpg",
    sourcePath: "ogamex-source/public/img/headers/resources/jungle_1_2_3_4.jpg",
    description: "Verdant-world resource header for colony and growth-focused panels.",
    tags: ["header", "resources", "jungle"],
  },
  {
    id: "ogamex-header-facilities-moon",
    name: "Moon Facilities Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/facilities/moon_3.jpg",
    sourcePath: "ogamex-source/public/img/headers/facilities/moon_3.jpg",
    description: "Lunar facility header for moonbase, phalanx, and orbital construction panels.",
    tags: ["header", "facilities", "moon"],
  },
  {
    id: "ogamex-header-shipyard",
    name: "Shipyard Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/shipyard/shipyard.jpg",
    sourcePath: "ogamex-source/public/img/headers/shipyard/shipyard.jpg",
    description: "Shipyard header artwork for fleet production and hull construction screens.",
    tags: ["header", "shipyard", "fleet"],
  },
  {
    id: "ogamex-header-rewards",
    name: "Rewards Header",
    category: OGAMEX_ASSET_CATEGORIES.HEADERS,
    path: "/assets/ogamex/headers/rewards/rewards.jpg",
    sourcePath: "ogamex-source/public/img/headers/rewards/rewards.jpg",
    description: "Rewards and progression header for season, achievement, and milestone panels.",
    tags: ["header", "rewards", "progression"],
  },
  {
    id: "ogamex-building-metal-mine",
    name: "Metal Mine",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/metal_mine_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/metal_mine_small.jpg",
    description: "OGameX metal mine preview image.",
    tags: ["building", "economy", "metal"],
  },
  {
    id: "ogamex-building-crystal-mine",
    name: "Crystal Mine",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/crystal_mine_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/crystal_mine_small.jpg",
    description: "OGameX crystal mine preview image.",
    tags: ["building", "economy", "crystal"],
  },
  {
    id: "ogamex-building-deuterium-synthesizer",
    name: "Deuterium Synthesizer",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/deuterium_synthesizer_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/deuterium_synthesizer_small.jpg",
    description: "OGameX deuterium synthesizer preview image.",
    tags: ["building", "economy", "deuterium"],
  },
  {
    id: "ogamex-building-solar-plant",
    name: "Solar Plant",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/solar_plant_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/solar_plant_small.jpg",
    description: "OGameX solar plant preview image for energy production cards.",
    tags: ["building", "energy", "solar"],
  },
  {
    id: "ogamex-building-robot-factory",
    name: "Robot Factory",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/robot_factory_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/robot_factory_small.jpg",
    description: "OGameX robot factory preview image for construction automation.",
    tags: ["building", "factory", "automation"],
  },
  {
    id: "ogamex-building-research-lab",
    name: "Research Lab",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/research_lab_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/research_lab_small.jpg",
    description: "OGameX research lab preview image for science infrastructure.",
    tags: ["building", "research", "lab"],
  },
  {
    id: "ogamex-building-shipyard",
    name: "Shipyard",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/shipyard_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/shipyard_small.jpg",
    description: "OGameX shipyard preview image for fleet construction panels.",
    tags: ["building", "shipyard", "fleet"],
  },
  {
    id: "ogamex-building-nanite-factory",
    name: "Nanite Factory",
    category: OGAMEX_ASSET_CATEGORIES.BUILDINGS,
    path: "/assets/ogamex/objects/buildings/nanite_factory_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/buildings/nanite_factory_small.jpg",
    description: "OGameX nanite factory preview image for advanced fabrication.",
    tags: ["building", "factory", "nanite"],
  },
  {
    id: "ogamex-research-energy-tech",
    name: "Energy Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/energy_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/energy_technology_small.jpg",
    description: "OGameX research panel art for energy technology.",
    tags: ["research", "energy", "technology"],
  },
  {
    id: "ogamex-research-hyperspace-drive",
    name: "Hyperspace Drive",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/hyperspace_drive_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/hyperspace_drive_small.jpg",
    description: "OGameX research panel art for hyperspace drive development.",
    tags: ["research", "drive", "hyperspace"],
  },
  {
    id: "ogamex-research-laser-tech",
    name: "Laser Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/laser_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/laser_technology_small.jpg",
    description: "OGameX research panel art for laser technology.",
    tags: ["research", "laser", "weapons"],
  },
  {
    id: "ogamex-research-plasma-tech",
    name: "Plasma Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/plasma_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/plasma_technology_small.jpg",
    description: "OGameX research panel art for plasma technology.",
    tags: ["research", "plasma", "weapons"],
  },
  {
    id: "ogamex-research-shielding-tech",
    name: "Shielding Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/shielding_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/shielding_technology_small.jpg",
    description: "OGameX research panel art for shielding technology.",
    tags: ["research", "shield", "defense"],
  },
  {
    id: "ogamex-research-armor-tech",
    name: "Armor Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/armor_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/armor_technology_small.jpg",
    description: "OGameX research panel art for armor technology.",
    tags: ["research", "armor", "defense"],
  },
  {
    id: "ogamex-research-computer-tech",
    name: "Computer Technology",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/computer_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/computer_technology_small.jpg",
    description: "OGameX research panel art for computer technology.",
    tags: ["research", "computer", "command"],
  },
  {
    id: "ogamex-research-astrophysics",
    name: "Astrophysics",
    category: OGAMEX_ASSET_CATEGORIES.RESEARCH,
    path: "/assets/ogamex/objects/research/astrophysics_technology_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/research/astrophysics_technology_small.jpg",
    description: "OGameX research panel art for astrophysics.",
    tags: ["research", "astrophysics", "expansion"],
  },
  {
    id: "ogamex-unit-light-fighter",
    name: "Light Fighter",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/light_fighter_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/light_fighter_small.jpg",
    description: "OGameX light fighter preview image for fleet cards.",
    tags: ["unit", "fighter", "fleet"],
  },
  {
    id: "ogamex-unit-battleship",
    name: "Battleship",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/battleship_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/battleship_small.jpg",
    description: "OGameX battleship preview image for capital fleet cards.",
    tags: ["unit", "battleship", "fleet"],
  },
  {
    id: "ogamex-unit-battlecruiser",
    name: "Battlecruiser",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/battlecruiser_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/battlecruiser_small.jpg",
    description: "OGameX battlecruiser preview image for advanced fleet cards.",
    tags: ["unit", "battlecruiser", "fleet"],
  },
  {
    id: "ogamex-unit-destroyer",
    name: "Destroyer",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/destroyer_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/destroyer_small.jpg",
    description: "OGameX destroyer preview image for heavy fleet cards.",
    tags: ["unit", "destroyer", "fleet"],
  },
  {
    id: "ogamex-unit-small-cargo",
    name: "Small Cargo",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/small_cargo_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/small_cargo_small.jpg",
    description: "OGameX cargo ship preview image for logistics panels.",
    tags: ["unit", "cargo", "fleet"],
  },
  {
    id: "ogamex-unit-colony-ship",
    name: "Colony Ship",
    category: OGAMEX_ASSET_CATEGORIES.UNITS,
    path: "/assets/ogamex/objects/units/colony_ship_small.jpg",
    sourcePath: "ogamex-source/public/img/objects/units/colony_ship_small.jpg",
    description: "OGameX colony ship preview image for expansion panels.",
    tags: ["unit", "colony", "expansion"],
  },
  {
    id: "ogamex-planet-moon-view",
    name: "Moon View",
    category: OGAMEX_ASSET_CATEGORIES.PLANETARY,
    path: "/assets/ogamex/planets/normal_moon_view.jpg",
    sourcePath: "ogamex-source/public/img/planets/normal_moon_view.jpg",
    description: "Classic moon surface view used for planetary presentation.",
    tags: ["planet", "moon", "surface"],
  },
  {
    id: "ogamex-generated-ui-sheet",
    name: "Original OGame-Inspired UI Sheet",
    category: OGAMEX_ASSET_CATEGORIES.GENERATED,
    path: "/assets/ogamex/generated/ogame-inspired-ui-sheet.png",
    sourcePath: "generated_images/ogame-inspired-ui-sheet.png",
    description: "Original generated sci-fi strategy UI sheet for panel, command deck, and shell textures.",
    tags: ["generated", "ui", "panel", "fleet", "research", "defense"],
  },
] as const;

export function getOgamexAssetById(id: string): OgamexAssetReference {
  const asset = OGAMEX_ASSET_COLLECTIONS.find((item) => item.id === id);
  if (!asset) {
    throw new Error(`Unknown OGameX asset id: ${id}`);
  }
  return asset;
}

export const OGAMEX_FEATURED_ASSETS = {
  BACKGROUND: getOgamexAssetById("ogamex-bg-main"),
  RESEARCH: getOgamexAssetById("ogamex-content-research"),
  SHIPS: getOgamexAssetById("ogamex-content-ships"),
  SHIPS_COMPACT: getOgamexAssetById("ogamex-content-ships-compact"),
  DEFENSE: getOgamexAssetById("ogamex-header-defense"),
  RESOURCE_HEADER: getOgamexAssetById("ogamex-header-resources-ice"),
  FACILITY_HEADER: getOgamexAssetById("ogamex-header-facilities-moon"),
  SHIPYARD_HEADER: getOgamexAssetById("ogamex-header-shipyard"),
  REWARDS_HEADER: getOgamexAssetById("ogamex-header-rewards"),
  MOON: getOgamexAssetById("ogamex-planet-moon-view"),
  UI_SHEET: getOgamexAssetById("ogamex-generated-ui-sheet"),
  METAL_MINE: getOgamexAssetById("ogamex-building-metal-mine"),
  CRYSTAL_MINE: getOgamexAssetById("ogamex-building-crystal-mine"),
  DEUTERIUM_SYNTHESIZER: getOgamexAssetById("ogamex-building-deuterium-synthesizer"),
  SOLAR_PLANT: getOgamexAssetById("ogamex-building-solar-plant"),
  ROBOT_FACTORY: getOgamexAssetById("ogamex-building-robot-factory"),
  RESEARCH_LAB: getOgamexAssetById("ogamex-building-research-lab"),
  SHIPYARD: getOgamexAssetById("ogamex-building-shipyard"),
  NANITE_FACTORY: getOgamexAssetById("ogamex-building-nanite-factory"),
  LIGHT_FIGHTER: getOgamexAssetById("ogamex-unit-light-fighter"),
  BATTLESHIP: getOgamexAssetById("ogamex-unit-battleship"),
  BATTLECRUISER: getOgamexAssetById("ogamex-unit-battlecruiser"),
  DESTROYER: getOgamexAssetById("ogamex-unit-destroyer"),
  SMALL_CARGO: getOgamexAssetById("ogamex-unit-small-cargo"),
  COLONY_SHIP: getOgamexAssetById("ogamex-unit-colony-ship"),
  LASER_TECH: getOgamexAssetById("ogamex-research-laser-tech"),
  PLASMA_TECH: getOgamexAssetById("ogamex-research-plasma-tech"),
  SHIELDING_TECH: getOgamexAssetById("ogamex-research-shielding-tech"),
  ARMOR_TECH: getOgamexAssetById("ogamex-research-armor-tech"),
  COMPUTER_TECH: getOgamexAssetById("ogamex-research-computer-tech"),
  ASTROPHYSICS: getOgamexAssetById("ogamex-research-astrophysics"),
} as const;

export function getOgamexAssetsByCategory(category: OgamexAssetCategory): OgamexAssetReference[] {
  return OGAMEX_ASSET_COLLECTIONS.filter((asset) => asset.category === category);
}
